### ISSUE TITLE
Login Callback "No api key found in request"

### ISSUE THREAD

**Issue by Huge-Puppy** [supabase/supabase-flutter#327]
**Describe the bug**
When logging in (either twitter, google, or clicking on the confirmation email with email+password), when the app tries to redirect back to my app I get the error:
```{"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}```

I'm building for web. The user is created in the database, and when manually redirect back to my app I am logged in. 

**To Reproduce**
1. Set up auth providers
2. deploy web project
3. try to login and see error on redirecting back to the app

**Expected behavior**
the providers should link back to my app, not give an error.

**Version:**
 - 1.2.2

**Additional context**
**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Initialization**
Here is my initialization code
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: '.env');
  logger.wtf(dotenv.env['SUPABASE_URL']);
  await Supabase.initialize(
    anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
    url: dotenv.env['SUPABASE_URL']!,
  );
  init();
  runApp(Phoenix(child: const MyApp()));
}
```

**Network Request Error**
<img width="869" alt="Screenshot 2023-01-11 at 11 15 33 AM" src="https://user-images.githubusercontent.com/32687987/211885939-b2e03bc7-f9f8-424d-bef3-e2a5cacece6e.png">

**Comment by Vinzent03** [comment]
Did you initialize Supabase with your apikey as stated [here](https://github.com/supabase/supabase-flutter#getting-started)? Do you have any stacktrace? May you share some of your code?

**Comment by Huge-Puppy** [comment]
I updated the issue with more code examples. You can also see the error for yourself by going to https://app.campaignguru.app

**Comment by Vinzent03** [comment]
Are you sure `dotenv.env['SUPABASE_URL']` is not null? I get an error when launching your website in chrome. May you share the code of your login as well? The requested url looks strange to me.

**Comment by Huge-Puppy** [comment]
Yes, I'm sure it's not null. The website should be working now. Here is the login code for password:
```
  @override
  Future<void> signupPassword(String email, String password) async {
    await supabase.auth.signUp(
      email: email,
      password: password,
      emailRedirectTo: kIsWeb ? null : 'app.campaignguru://login-callback/',
    );
  }
```

**Comment by Huge-Puppy** [comment]
Here are my supabase auth url configurations:
<img width="969" alt="Screenshot 2023-01-11 at 3 26 26 PM" src="https://user-images.githubusercontent.com/32687987/211931382-a69c5fde-f0d8-4973-8fd9-5bb5b65d095b.png">

**Comment by dshukertjr** [comment]
@Huge-Puppy 
Could you try entering `https://app.campaignguru.app` instead of just `app.campaignguru.app`?

**Comment by Huge-Puppy** [comment]
> @Huge-Puppy 
> Could you try entering `https://app.campaignguru.app` instead of just `app.campaignguru.app`?

That fixed it! Thank you so much for helping out 💪

**Comment by sonnyvesali** [comment]
This solution still doesn't fix it for me, I just end up getting a link like this https://com.supabase_auth_sandbox.app//login-callback#access_token=abc&refresh_token=xyz&token_type=bearer and it doesn't go back to the app @dshukertjr, any other possible solutions? 

Thanks in advance :)

**Comment by sonnyvesali** [comment]
> This solution still doesn't fix it for me, I just end up getting a link like this https://com.supabase_auth_sandbox.app//login-callback#access_token=abc&refresh_token=xyz&token_type=bearer and it doesn't go back to the app @dshukertjr, any other possible solutions?
> 
> Thanks in advance :)

<img width="882" alt="Screenshot 2023-04-25 at 3 45 39 PM" src="https://user-images.githubusercontent.com/79886185/234399521-5cf63711-b633-46ce-8061-aeaf8ed52e2c.png">
^^ Supabase dashboard

Local flutter code 

```dart
 await auth.signInWithOAuth(
    Provider.google,
    scopes: 'email profile openid',
    authScreenLaunchMode: LaunchMode.platformDefault,
    redirectTo: kIsWeb
        ? null
        : 'https://com.supabase_auth_sandbox.app://login-callback',
  );
```

**Comment by dshukertjr** [comment]
@sonnyvesali 
Have you configured deep links as described here?
https://pub.dev/packages/supabase_flutter#deep-link-config
