### ISSUE TITLE
Flutter Web - Code verifier could not be found in local storage

### ISSUE THREAD

**Issue by muezz** [supabase/supabase-flutter#836]
In flutter web, I am trying to authenticate the user by calling this:
```dart
await Supabase.instance.client.auth.signInWithOAuth(OAuthProvider.google, redirectTo: 'http://localhost:5000/login');
```
But I get the following error:
``` console
Error: AuthException(message: Code verifier could not be found in local storage., statusCode: null)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/gotrue/src/gotrue_client.dart 301:7                                 exchangeCodeForSession
```

**Comment by dshukertjr** [comment]
What is the URL of the page that initiates the Google login process?

**Comment by muezz** [comment]
@dshukertjr My app is on `http://localhost:5000/login` when I click on the login button which opens a popup where I can sign into google or if that is already done I can choose an account. After that, I am taken back to the login page but the url has a query param called code.

**Comment by dshukertjr** [comment]
Hmm, `signInWithOAuth()` should not open a popup, but should perform a redirect to the Google sign-in screen. 

Could you share a screen recording of walking through the sign-in process?

**Comment by muezz** [comment]
This is really weird. When I was trying last night, it was definitely opening a popup. I just tried it now and it automatically logs me in because the chrome session already has my profile. I tried in an incognito window and it redirected me to a google sign in page. 

So, in short, I am not seeing the popup. Also, the code verifier bug does not happen after signing in. If I reload the page while the `code` is still in the URL, then I get the error which is not really a realistic scenario as I expect to be redirected to another URL once the user has been authorized.

Side question: If I check the `currentUser` right after calling `signInWithOAuth()`, I get null. I think that is expected as the docs say that I need to listen for auth state change in the change listener. Is there a way to avoid that? I would really like to keep my business logic in one place because it is tightly coupled with some other custom logic.

There must be a way because Firebase allows it. I am not sure how they do it without ID Token though.

**Comment by dshukertjr** [comment]
>When I was trying last night, it was definitely opening a popup. I just tried it now and it automatically logs me in because the chrome session already has my profile. I tried in an incognito window and it redirected me to a google sign in page.

Hmm, that is weird. If it happens again, please don't hesitate to report it!

>If I check the currentUser right after calling signInWithOAuth(), I get null. I think that is expected as the docs say that I need to listen for auth state change in the change listener. Is there a way to avoid that? I would really like to keep my business logic in one place because it is tightly coupled with some other custom logic. 
>
>There must be a way because Firebase allows it. I am not sure how they do it without ID Token though.

Yeah, there is a slight delay after the redirect until the session is retrieved. Currently, the only way to retrieve the session and user safely is to listen to onAuthStateChange.

**Comment by bqubique** [comment]
I'm having this same issue after I Restart the app (generally when a Save action is performed on VSCode which triggers the hot restart). Then I get this:
```AuthException(message: Code verifier could not be found in local storage., statusCode: null)```
Although right above this error I get the accessToken, refreshToken printed fine!

`
{"access_token":"___","expires_in":3600,"expires_at":___,"refresh_token":"___","token_type":"bearer","provider_token":"___","provider_refresh_token":null,"user":{"id":"___","app_metadata":{"provider":"google","providers":["google"]},"user_metadata":{"avatar_url":"___","email":"b***@gmail.com","email_verified":true,"full_name":"Blin Qipa","iss":"https://accounts.google.com","name":"Blin Qipa","phone_verified":false,"picture":"___","provider_id":"___","sub":"___"},"aud":"authenticated","confirmation_sent_at":null,"recovery_sent_at":null,"email_change_sent_at":null,"new_email":null,"invited_at":null,"action_link":null,"email":"b****@gmail.com","phone":"","created_at":"2024-08-13T16:31:21.659669Z","confirmed_at":"2024-08-13T16:31:21.699634Z","email_confirmed_at":"___","phone_confirmed_at":null,"last_sign_in_at":"___","role":"authenticated","updated_at":"___","identities":[{"id":"___","user_id":"___","identity_data":{"avatar_url":"___","email":"b****@gmail.com","email_verified":true,"full_name":"Blin Qipa","iss":"https://accounts.google.com","name":"Blin Qipa","phone_verified":false,"picture":"___","provider_id":"___","sub":"___"},"identity_id":"___","provider":"google","created_at":"___","last_sign_in_at":"___","updated_at":"___"}],"factors":null,"is_anonymous":false}}
`

(___ and *** are written in case to hide credentials/important data, otherwise they're available).
This only occurs on Flutter web.)

<details><summary>Details</summary>
<p>

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0 on channel stable at /Users/blinqipa/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/blinqipa/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120
    ! Error: Browsing on the local area network for Blin’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

</p>
</details>

**Comment by hansaliyad1** [comment]
> So, in short, I am not seeing the popup. Also, the code verifier bug does not happen after signing in. If I reload the page while the code is still in the URL, then I get the error which is not really a realistic scenario as I expect to be redirected to another URL once the user has been authorized.

@dshukertjr This is happening to me. Like @muezz  mentioned here.

**Comment by jacobhong** [comment]
same thing is happening to me and I thought I was going crazy. In localhost debug mode I intermittently get the stupid login error that code could not be found. After logging in and out / refreshing page for a few hours it goes away with no code change. I deployed to prod and encountered the issue and tried to fix for several hours only for it to randomly go away. Please reopen this. 

Also the redirectTo does not seem to be working
```
                  await Supabase.instance.client.auth.signInWithOAuth(
                    OAuthProvider.google,
                    redirectTo: const String.fromEnvironment('REDIRECT_URI'),
                    scopes:
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                    queryParams: {
                      "access_type": "offline",
                      "prompt": "consent",
                    },
                  );
                  
```
I have even tried hard coding redirectTo and it just defaults to SITE_URL in dashboard. I have 100% correct redirect URI setup in additional redirects.

**Comment by jacobhong** [comment]
@dshukertjr  Ill try to post some code samples later and versions info but I just realized something from testing
1) click google sign in
2) complete auth flow
3) redirected back to my home page and logged in
3) a observe url has a code appended to it 'htts://example.com?code=123xyz
4) refresh page
5) logged out and says code auth exception

At this point every time I login and refresh it fails with the above exception. I notice if I just manually load the url without the code appended, I am still logged in and everything works, even refreshing.

During local dev I am redirected back to 'http://localhost:3000' but no code appended, and it works fine. Not sure why in prod with my custom domain it appends ?code and fails saying code not found.

**Comment by silverhairs** [comment]
Any update on this issue? it's still happening on flutter web

Package: ` supabase_flutter: ^2.8.4`.
Environment: localhost

## Steps to reproduce
- Implement signin with Google following [the steps in the docs](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=platform&platform=flutter#web-macos-windows-and-linux)
- Listen to auth changes via `supabase.auth.onAuthStateChange`.
- Sign in with google (works fine).
- Refresh the page

## Outcome:
You are logged out and the error below is logged:
```
AuthException(message: Code verifier could not be found in local storage., statusCode:
null, errorCode: null)
```
## Expected Outcome:
Session is kept and you are still logged in.

**Comment by hansaliyad1** [comment]
@silverhairs I don't think so. I follow the workaround provided by @jacobhong

**Comment by maprohu** [comment]
Hi! I have just run into a similar issue. Actually I receive the same error message when I register a new user and then get redirected back to the Flutter app after clicking on the link in the confirmation email. I am using user/password authentication, not OAuth.

In my case, I am running the Flutter app in dev mode, which will open its own instance of Chrome (I am using Flutter web). And then when I receive the email and click on it, it will open my default browser, which will be a different instance of Chrome, not the same one where I registered the user. (So they will not share the local storage.)

As it happens, if I do open the confirmation link in the same browser where I registered the user, it seems to work fine, I do not get the error message saying "Code verifier could not be found in local storage". 

It feels as if the Supabase library will assume that the confirmation link will be opened in the very same browser where I registered the user. I am not sure if this is really the case, but if it is, then it does not seem reasonable to me. I may be working on my desktop and may want to quickly click the confirmation link on my phone as i receive the notification about the email. 

Am I right that this may be a design issue?

**Comment by jacobhong** [comment]
in a new project using a newer version of supabase 2.9.1 I don't have this issue anymore, my old project was on 2.6.0.

**Comment by LukmanHadi07** [comment]
Hi, I also experienced this when using 0Auth supabase to login with google, is there any solution to solve this case in flutter?
